version: "3.9"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=mysql # El nombre del host para la base de datos sigue siendo 'mysql' (nombre del servicio)
      - DB_PORT=3307  # Actualizamos el puerto de conexión a MySQL para la app
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --port=3307 # Hacemos que MySQL escuche en el puerto 3307 dentro del contenedor
    ports:
      - "3307:3307" # Mapeamos el puerto 3307 del contenedor al puerto 3307 del host
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80" # Accede a phpMyAdmin en http://localhost:8081
    environment:
      - PMA_HOST=mysql # El host para phpMyAdmin sigue siendo 'mysql'
      - PMA_PORT=3307  # Actualizamos el puerto de conexión a MySQL para phpMyAdmin
    depends_on:
      - mysql

volumes:
  mysql_data: