version: "3.9"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=Duoc4229@!
      - DB_USER=ferremas
      - DB_NAME=ferremas
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Duoc4229@! # Change this!
      - MYSQL_DATABASE=ferremas
      - MYSQL_USER=ferremas
      - MYSQL_PASSWORD=Duoc4229@!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80" # Accede a phpMyAdmin en http://localhost:8081
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

volumes:
  mysql_data: